# Nome do Workflow
name: Backend Pipeline - Hackathon

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
      name: Build
      runs-on: ubuntu-latest
      steps: 
        - name: Clone do Repositório
          uses: actions/checkout@v2

        - name: Login no Google Artifact Registry
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          run: | 
            echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
            cat key.json | docker login -u _json_key --password-stdin https://us-east4-docker.pkg.dev/

        - name: Build Imag & Push para Google Registry
          env: 
            ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
          run: | 
            docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/backend:latest .
            docker push ${{ secrets.ARTIFACT_REGISTRY }}/backend:latest

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone do Repositório
        uses: actions/checkout@v2

      - name: Autenticação no Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy Backend no  Cloud Run
        id: deploy
        run: |-
          gcloud run deploy backend \
            --quiet \
            --region  ${{ secrets.GOOGLE_REGION }} \
            --image ${{ secrets.ARTIFACT_REGISTRY }}/backend:latest \
            --platform managed \
            --set-env-vars CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONNECTION_NAME }},CLOUD_SQL_DATABASE_NAME=${{ secrets.CLOUD_SQL_DATABASE_NAME }},CLOUD_SQL_PASSWORD=${{ secrets.CLOUD_SQL_PASSWORD }},CLOUD_SQL_USERNAME=${{ secrets.CLOUD_SQL_USERNAME }} \
            --allow-unauthenticated \
            --add-cloudsql-instances ${{ secrets.CLOUD_SQL_CONNECTION_NAME }} \
            --project ${{ secrets.GOOGLE_PROJECT_ID }} \
            --format json